In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
vector = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print(vector)
print(len(vector))
vector[3] = 1
print(vector)

for valor in vector:
    print(valor)

In [6]:
print("ndarray.shape: devuelve la dimensión de una matriz (número de filas y columnas).", vector.shape)
print("ndarray.ndim: devuelve el número de dimensiones de la matriz.", vector.ndim)
print("ndarray.size: devuelve el número total de elementos de la matriz.", vector.size)
print("ndarray.dtype: devuelve el tipo de datos de los elementos de la matriz.", vector.dtype)
print("ndarray.itemsize: devuelve el tamaño en bytes de los elementos de la matriz.", vector.itemsize)
print("ndarray.data: devuelve un búfer que contiene los elementos actuales de la matriz.", vector.data)


ndarray.shape: devuelve la dimensión de una matriz (número de filas y columnas). (10,)
ndarray.ndim: devuelve el número de dimensiones de la matriz. 1
ndarray.size: devuelve el número total de elementos de la matriz. 10
ndarray.dtype: devuelve el tipo de datos de los elementos de la matriz. int64
ndarray.itemsize: devuelve el tamaño en bytes de los elementos de la matriz. 8
ndarray.data: devuelve un búfer que contiene los elementos actuales de la matriz. <memory at 0x11da98100>


In [ ]:
# Métodos:
# np.array(): crea una matriz a partir de una secuencia de datos.
# np.zeros(): crea una matriz de ceros con una forma específica.
# np.ones(): crea una matriz de unos con una forma específica.
# np.full(): crea una matriz con un valor constante con una forma específica.
# ndarray.reshape(): cambia la forma de una matriz.
# ndarray.transpose(): transpone una matriz.
# ndarray.flatten(): convierte una matriz en un array de una dimensión.
# ndarray.max(): devuelve el valor máximo de una matriz.
# ndarray.min(): devuelve el valor mínimo de una matriz.
# ndarray.sum(): devuelve la suma de los elementos de una matriz.
# ndarray.mean(): devuelve la media de los elementos de una matriz.
# ndarray.std(): devuelve la desviación estándar de los elementos de una matriz.
# np.dot(): realiza la multiplicación matricial entre dos matrices.
# np.random.rand(): genera una matriz de números aleatorios entre 0 y 1.

print()

In [9]:
matriz = np.array(([1, 1, 1, 1], [2, 2, 2, 2], [3, 3, 3, 3], [4, 4, 4, 4]))
print(matriz)
print(len(matriz))
print(matriz[3])
print(matriz.shape)

[[1 1 1 1]
 [2 2 2 2]
 [3 3 3 3]
 [4 4 4 4]]
4
[4 4 4 4]
(4, 4)


In [ ]:
# Ejercicios Numpy
# Crear un arreglo 3x3 de numpy con todas las entradas igual a True

def ejercicio1():
    matriz = np.ones((3, 3), dtype=bool)
    print(matriz)
    
ejercicio1()


[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]
[ 0 -1  2 -1  4 -1  6 -1  8 -1]


In [11]:
# Reemplazar todos los numeros impares del sigueinte arreglo por el valor de -1. arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

def ejercicio2():
    arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
    arr[arr % 2 == 1] = -1
    print(arr)
    
ejercicio2()

[ 0 -1  2 -1  4 -1  6 -1  8 -1]


In [8]:
# Convertir el Siguiente arreglo 1D a un arreglo 2D. arr = np.array([ 0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

def ejercicio3():
    arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
    arr = arr.reshape(2, -1)
    print(arr)
    
ejercicio3()

[[0 1 2 3 4]
 [5 6 7 8 9]]
